# =======================================================
# 1. BASE CONFIGURATION (applies if no profile is active)
# =======================================================
spring:
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

# =======================================================
# 2. DEVELOPMENT PROFILE (H2 - quick local testing)
# =======================================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:taskdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

# =======================================================
# 3. PRODUCTION PROFILE (PostgreSQL - Docker)
# =======================================================
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://task-postgres:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true